org.gradle.jvmargs=-Xmx2048M

# ============================================================
#  BRANCH-SPECIFIC: must match the git branch name.
#  Switch branches? Run:  git checkout -- gradle.properties
#  The build will refuse to run if this doesn't match.
# ============================================================
minecraft_version=26.2
enabled_platforms=fabric,neoforge,neoforge

archives_base_name=BetterRecipeBookExtended
mod_version=2.1.4c
maven_group=com.alonie.brbe

# Mod Loaders
fabric_loader_version=0.19.3
neoforge_version = 26.2.0.1-beta

# Depends
architectury_version=21.0.1
fabric_api_version=0.152.1+26.2
cloth_config_version=26.2.155
modmenu_version=17.0.0-beta.2

# compat
mouse_wheelie_version=1.13.3+mc1.20.4
org.gradle.jvmargs=-Xmx2048M -Dnet.minecraft.gradle.deprecated=true

