dependencies {
    compileOnly "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    compileOnly("dev.architectury:architectury-fabric:${rootProject.architectury_version}") {
        exclude group: "net.fabricmc.fabric-api"
    }
    compileOnly "me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}"
}
