package com.alonie.brbe.cache;

import com.alonie.brbe.BetterRecipeBook;
import net.minecraft.client.ClientRecipeBook;
import net.minecraft.world.item.crafting.display.RecipeDisplayEntry;
import net.minecraft.world.item.crafting.display.RecipeDisplayId;

import java.util.*;

/**
 * Local vanilla recipe cache that supplements server-provided recipes.
 *
 * Recipes are loaded from the classpath (Minecraft JAR) at startup by
 * {@link VanillaRecipeLoader} — no file I/O, no singleplayer capture needed.
 *
 * On recipe-sparse servers (known.size() &lt; 50), cached entries are injected
 * into {@link ClientRecipeBook#known} before rebuildCollections().
 *
 * <h3>ID-space partition</h3>
 * Cache entries use <b>negative</b> {@link RecipeDisplayId} values (starting
 * at -1, decrementing).  Server-assigned IDs are always non-negative.  This
 * creates a hard partition: {@code isLocalRecipe(id)} is simply
 * {@code id.index() &lt; 0}, with zero collision risk regardless of what IDs
 * the server sends later.
 */
public final class VanillaRecipeCache {

    /** Maximum known recipes to consider server "sparse" and trigger injection. */
    private static final int SPARSE_THRESHOLD = 50;

    // ---- State ----

    /** All cached vanilla recipe entries, loaded at init from classpath. */
    private static final Map<String, CacheableRecipeDisplayEntry> cache = new LinkedHashMap<>();

    private VanillaRecipeCache() {}

    // ---- Lifecycle ----

    /** Called once from BetterRecipeBook.init(). Loads vanilla recipes from classpath. */
    public static void init() {
        cache.clear();
        List<CacheableRecipeDisplayEntry> loaded = VanillaRecipeLoader.loadAll();
        for (CacheableRecipeDisplayEntry entry : loaded) {
            if (entry != null && entry.recipeKey() != null) {
                cache.put(entry.recipeKey(), entry);
            }
        }
        BetterRecipeBook.LOGGER.info("[BRBE-CACHE] init loaded {} vanilla recipes from classpath",
                cache.size());
    }

    /** Called from MinecraftMixin on disconnect. Resets session-only state. */
    public static void clear() {
        // No session-state set to clear — negative-ID entries are naturally
        // discarded when Minecraft creates a fresh ClientRecipeBook on reconnect.
        BetterRecipeBook.LOGGER.info("[BRBE-CACHE] session cleared");
    }

    // ---- Detection and orchestration ----

    /**
     * Called before ClientRecipeBook.rebuildCollections().
     * If the server looks recipe-sparse and we have a cache, inject entries.
     */
    public static void detectAndInject(ClientRecipeBook recipeBook,
                                        Map<RecipeDisplayId, RecipeDisplayEntry> known) {
        if (cache.isEmpty()) return;

        int count = known.size();
        BetterRecipeBook.LOGGER.info("[BRBE-CACHE] pre-rebuild known count: {}", count);

        if (count < SPARSE_THRESHOLD) {
            // Purge any previously-injected cache entries (negative IDs) before
            // re-injecting.  This is safe because server IDs are always ≥ 0.
            known.keySet().removeIf(id -> id.index() < 0);
            injectInto(recipeBook, known);
        }
    }

    // ---- Inject ----

    private static void injectInto(ClientRecipeBook recipeBook,
                                    Map<RecipeDisplayId, RecipeDisplayEntry> known) {
        int nextId = -1; // cache IDs are negative — never collide with server IDs (≥ 0)
        int injectedCount = 0;

        for (CacheableRecipeDisplayEntry cEntry : cache.values()) {
            try {
                RecipeDisplayId newId = new RecipeDisplayId(nextId--);
                RecipeDisplayEntry entry = cEntry.toEntry(newId);
                if (entry != null) {
                    known.put(newId, entry);
                    injectedCount++;
                }
            } catch (Exception e) {
                BetterRecipeBook.LOGGER.warn(
                        "[BRBE-CACHE] failed to reconstruct entry {}: {}",
                        cEntry.recipeKey(), e.getMessage());
            }
        }

        BetterRecipeBook.LOGGER.info(
                "[BRBE-CACHE] injected {} cached entries (known now {})",
                injectedCount, known.size());
    }

    // ---- Queries ----

    /**
     * Returns true if {@code id} was generated by the local cache rather than
     * the server.  Cache entries always use negative indices; server IDs are
     * always non-negative, so this is a zero-collision check.
     */
    public static boolean isLocalRecipe(RecipeDisplayId id) {
        return id.index() < 0;
    }

    public static boolean hasEntries() {
        return !cache.isEmpty();
    }

    public static int cacheSize() { return cache.size(); }
}
